export const heraldsAndOrders = [
  { 
    name: "Jezrien", 
    order: "Windrunners", 
    description: "Associated with Gravitation and Adhesion. Known for protecting and leading.", 
    image: "/heralds/Jezrien.jpg",
    surges: ["Gravitation", "Adhesion"],
    radiantGlyph: "/knights-glyphs/Windrunners_glyph.svg",
    spren: "Honorspren",
  },
  { 
    name: "Nale", 
    order: "Skybreakers", 
    description: "Associated with Gravitation and Division. Known for upholding justice and confidence.", 
    image: "/heralds/Nale.jpg",
    surges: ["Gravitation", "Division"],
    radiantGlyph: "/knights-glyphs/Skybreakers_glyph.svg",
    spren: "Highspren", 
  },
  { 
    name: "Chanarach", 
    order: "Dustbringers", 
    description: "Associated with Division and Abrasion. Known for bravery and obedience.", 
    image: "/heralds/Chanarach.jpg",
    surges: ["Division", "Abrasion"],
    radiantGlyph: "/knights-glyphs/Dustbringers_glyph.svg",
    spren: "Ashspren", 
  },
  { 
    name: "Vedel", 
    order: "Edgedancers", 
    description: "Associated with Abrasion and Progression. Known for their love and healing.", 
    image: "/heralds/Vedel.jpg",
    surges: ["Abrasion", "Progression"],
    radiantGlyph: "/knights-glyphs/Edgedancers_glyph.svg",
    spren: "Cultivationspren",
  },
  { 
    name: "Pailiah", 
    order: "Truthwatchers", 
    description: "Associated with Progression and Illumination. Known for being learned and giving.", 
    image: "/heralds/Pailiah.jpg",
    surges: ["Progression", "Illumination"],
    radiantGlyph: "/knights-glyphs/Truthwatchers_glyph.svg",
    spren: "Mistspren", 
  },
  { 
    name: "Shalash", 
    order: "Lightweavers", 
    description: "Associated with Illumination and Transformation. Known for creativity and honesty.", 
    image: "/heralds/Shalash.jpg",
    surges: ["Illumination", "Transformation"],
    radiantGlyph: "/knights-glyphs/Lightweavers_glyph.svg",
    spren: "Cryptic", 
  },
  { 
    name: "Battar", 
    order: "Elsecallers", 
    description: "Associated with Transformation and Transportation. Known for wisdom and carefulness.", 
    image: "/heralds/Battar.jpg",
    surges: ["Transformation", "Transportation"],
    radiantGlyph: "/knights-glyphs/Elsecallers_glyph.svg",
    spren: "Inkspren", 
  },
  { 
    name: "Kalak", 
    order: "Willshapers", 
    description: "Associated with Transportation and Cohesion. Known for resolve and building.", 
    image: "/heralds/Kalak.jpg",
    surges: ["Transportation", "Cohesion"],
    radiantGlyph: "/knights-glyphs/Willshapers_glyph.svg",
    spren: "Reacher", 
  },
  { 
    name: "Talenel", 
    order: "Stonewards", 
    description: "Associated with Cohesion and Tension. Known for dependability and resourcefulness.", 
    image: "/heralds/Talenel.jpg",
    surges: ["Cohesion", "Tension"],
    radiantGlyph: "/knights-glyphs/Stonewards_glyph.svg",
    spren: "Peakspren", 
  },
  { 
    name: "Ishar", 
    order: "Bondsmiths", 
    description: "Associated with Tension and Adhesion. Known for piety and leadership.", 
    image: "/heralds/Ishar.jpg",
    surges: ["Tension", "Adhesion"],
    radiantGlyph: "/knights-glyphs/Bondsmiths_glyph.svg",
    spren: "Stormfather, Nightwatcher, Sibling", 
  },
];
  

export const surges = [  
      { 
        name: "Gravitation", 
        description: "This surge allows the user to control gravity. By manipulating the gravitational pull on objects or themselves, they can make things float, walk on walls, or even become completely weightless. It can direct gravity to create levitation effects or pull users towards specific points, giving them tremendous mobility in combat or movement.",
        glyph: '/surges/Gravitation_Surge-glyph.svg',
      },
      { 
        name: "Adhesion", 
        description: "This surge enables the user to create physical bonds between objects or surfaces. Users can make objects stick together, bind things with great force, or even \"stick\" to surfaces, making it useful for climbing or holding enemies in place. The surge is versatile, allowing for both offensive and defensive applications, as well as aiding mobility.",
        glyph: '/surges/Adhesion_Surge-glyph.svg',
      },
      { 
        name: "Division", 
        description: "This surge enables the user to break down matter at a molecular level. It is used to disintegrate objects or enemies by reducing them to their constituent particles. It’s a destructive and fearsome power that can obliterate solid structures or tear through enemies with precision.",
        glyph: '/surges/Division_Surge-glyph.svg',
      },
      { 
        name: "Abrasion", 
        description: "This surge alters the friction between objects or surfaces, allowing users to either increase or reduce it. By increasing friction, users can create a strong, sticky effect, preventing movement. Conversely, reducing friction allows them to glide over surfaces with ease or move rapidly without resistance. Abrasion is also highly useful in combat for making enemies slip or lose their balance.",
        glyph: '/surges/Abrasion_Surge-glyph.svg',
      },
      { 
        name: "Progression", 
        description: "This surge allows the user to accelerate growth, whether of plants or living beings. It has powerful healing capabilities, allowing users to rapidly heal injuries, accelerate the growth of plants for defensive or utilitarian purposes, or nurture life around them. The surge can be used to regenerate tissue or encourage the rapid blooming of flowers, offering both combat and restorative benefits.",
        glyph: '/surges/Progression_Surge-glyph.svg',
      },
      { 
        name: "Illumination", 
        description: "This surge allows the manipulation of light and sound, creating illusions, hiding in plain sight, or distorting perception. Users can use this ability to obscure their presence, create false images, or confuse enemies. The surge is often used for stealth or misdirection, making it a key tool for deception or avoidance.",
        glyph: '/surges/Illumination_Surge-glyph.svg',
      },
      { 
        name: "Transformation", 
        description: "The ability to alter the physical properties of objects, turning one material into another, is the essence of this surge. Users can transmute materials into something entirely different, such as changing stone into gold or fabric into water. This surge is often used creatively in both combat and artistic endeavors, allowing for rapid changes to the environment.",
        glyph: '/surges/Transformation_Surge-glyph.svg',
      },
      { 
        name: "Transportation", 
        description: "This surge allows the user to move instantaneously from one place to another, whether across vast distances or between different realms entirely. Users can teleport, making them incredibly elusive and capable of reaching distant places in the blink of an eye. This surge is crucial for rapid movement and access to otherwise unreachable locations.",
        glyph: '/surges/Transportation_Surge-glyph.svg',
      },
      { 
        name: "Cohesion", 
        description: "This surge allows the user to manipulate the internal structure of materials, either increasing or decreasing their rigidity. Users can reshape solid objects, making them stronger, more flexible, or entirely different in structure. The ability to bind or separate materials gives them a creative edge in battle and construction.",
        glyph: '/surges/Cohesion_Surge-glyph.svg',
      },
      { 
        name: "Tension", 
        description: "This surge allows the user to alter the flexibility of materials. They can make things stiffer or more pliable, even changing the physical properties of objects to make them more or less resistant to stress. This surge is key in defensive and combat applications, allowing users to make things more durable or, conversely, weaken them.",
        glyph: '/surges/Tension_Surge-glyph.svg',
      },
];
